# Upload some file
POST http://localhost:3000/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="file-storage.png"
Content-Type: image/png

< /home/fantastic_fox/avatar-test.png

--boundary--

###

# Get file by ID
GET http://localhost:3000/api/files/68af21c9b7e2ffa28c2ae410 HTTP/1.1

###
