###

# Get posts
GET http://localhost:3000/api/posts

###

# Create video post
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json

{
  "tags": [
    "test"
  ],
  "status": "published",
  "repost": false,
  "authorId": "123",
  "type": "video",
  "videoPost": {
    "title": "How to Build NestJS App",
    "videoLink": "https://youtube.com/watch?v=abc123"
  }
}

###

# Detail post info
GET http://localhost:3000/api/posts/11b95821-6bd8-4c80-946f-b50e34659e75 HTTP/1.1
Content-Type: application/json

###

# Update post
PATCH http://localhost:3000/api/posts/11b95821-6bd8-4c80-946f-b50e34659e75 HTTP/1.1
Content-Type: application/json

{
  "tags": [
    "programming",
    "tutorial2"
  ],
  "status": "published",
  "repost": false,
  "authorId": "333",
  "type": "video",
  "title": "How to Build NestJS App2",
  "videoLink": "https://youtube.com/watch?v=abc123"
}

###

# Delete post
DELETE http://localhost:3000/api/posts/b5ed0201-9f42-4603-9e74-026df8a907f1 HTTP/1.1
Content-Type: application/json

###
