###

# Get posts
GET http://localhost:3000/api/posts

###

# Create post
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json

{
  "tags": "['тест', 'тест2']",
  "status": "publish",
  "publishAt": "2025-08-11T07:01:32.001Z",
  "updatedAt": "2025-08-11T07:01:32.001Z",
  "repost": false,
  "repostAuthor": 123,
  "author": "123",
  "type": "photo",
  "photo": "./text.png"
}

###

# Detail post info
GET http://localhost:3000/api/posts/1052b7ec-f984-4f5e-9ef1-e975400069ef HTTP/1.1
Content-Type: application/json

###

# Update post
PATCH http://localhost:3000/api/posts/d3d63d04-922f-4475-8756-45c306fd94e4 HTTP/1.1
Content-Type: application/json

{
  "tags": "['тест3', 'тест4']"
}

###

# Delete post
DELETE http://localhost:3000/api/posts/fd5803e9-1cfe-4dac-95a7-ceb19360bde8 HTTP/1.1
Content-Type: application/json

###
